language: python
install:
  - pip install coveralls coverage pep8
python:
  - "2.7"
script:
  - ./shm_instrumentation.py
  - make testcase
  - echo 'a' | ./apr-showmap -o /dev/stdout ./testcase
  - coverage run ./shm_instrumentation.py
  - echo 'a' | coverage run ./apr-showmap -o /dev/stdout ./testcase
  - coverage report
  - pep8 apr-showmap apr-fuzz *.py
