language: python
install:
  - pip install coveralls coverage
python:
  - "2.7"
script:
  - coverage run shm_instrumentation.py
  - make testcase ; echo 'a' | coverage run ./apr-showmap -o /dev/stdout ./testcase
  - coverage report
